Description: Create resources for a simple Jenkins build environment
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair
    Type: String
  Region:
    Description: AWS Region
    Type: String
    AllowedValues: [us-east-1, us-west-1, us-east-2, us-west-2]
Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-047a51fa27710816e
    us-west-1:
      AMI: ami-005c06c6de69aee84
    us-east-2:
      AMI: ami-01aab85a5e4a5a0fe
    us-west-2:
      AMI: ami-0e999cbd62129e3b1
Resources:
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
  JenkinsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP and open port 8080 on TCP
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
        - CidrIp: 0.0.0.0/0
          FromPort: 8080
          IpProtocol: tcp
          ToPort: 8080
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      KeyName: !Ref KeyName
      ImageId: !FindInMap [RegionMap, !Ref Region, AMI]
      InstanceType: t2.micro
      SecurityGroups: [!Ref SSHSecurityGroup, !Ref JenkinsSecurityGroup]
Outputs:
  PublicIP:
    Value: !GetAtt EC2Instance.PublicIp
    Description: Instance's public IP address